services:
  db:
    image: mariadb:11
    container_name: fashion_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: fashion_catalog_db
      MARIADB_USER: fashion_user
      MARIADB_PASSWORD: fashion_pass
      MARIADB_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: fashion_api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      CI_ENVIRONMENT: development
    volumes:
      - .:/var/www/html
      - ./writable:/var/www/html/writable
volumes:
  db_data:
